site_name: Net Promoter Score
site_url: https://manutechwriter.github.io/npstest/
extra_css:
  - stylesheets/extra.css
nav:
    - Home: index.md
    - Updates (NEW): updates.md
    - Live Chart (NEW): live-chart.md
theme:
    name: material
    palette:
      - scheme: default
        primary: black
        toggle:
          icon: material/toggle-switch
          name: Switch to dark mode
      - scheme: slate
        primary: white
        toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to light mode
    features:
        - content.code.copy
        - content.action.edit
        - search.suggest
        - navigation.tabs
        - navigation.tracking
        - navigation.instant
        - navigation.top

repo_url: https://github.com/manutechwriter/npstest
edit_uri: edit/main/docs/


markdown_extensions:
- attr_list
- md_in_html
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.highlight:
      anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- admonition
- pymdownx.details
- pymdownx.superfences:
    custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
