site_name: Net Promoter Score
site_url: https://example.com/
extra_css:
  - stylesheets/extra.css
nav:
    - Home: index.md
theme:
    name: material
    palette:
        primary: black
    features:
        - content.code.copy




markdown_extensions:
- attr_list
- md_in_html
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.highlight:
      anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- admonition
- pymdownx.details
- pymdownx.superfences:
    custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


